basePath: /api
consumes: [application/json]
definitions:
  Plusoneret:
    properties:
      apiversion: {description: '', type: integer}
      plusoneret: {description: '', type: integer}
    required: [plusoneret, apiversion]
    title: plusoneret
    type: object
  Request:
    properties:
      request: {description: '', type: string}
    required: [request]
    title: request
    type: object
  Response:
    properties:
      apiversion: {description: '', type: integer}
      count: {description: '', type: integer}
      currentvisit: {description: '', format: date-time, type: string}
      response: {description: '', type: string}
    required: [response, currentvisit, count, apiversion]
    title: response
    type: object
host: 172.17.0.49:80
info:
  license: {name: GPL, url: 'https://www.gnu.org/licenses/gpl-3.0.en.html'}
  title: helloService
  version: '2.0'
paths:
  /hello:
    post:
      description: Reflect anything user input
      operationId: app.hello_sv
      parameters:
      - description: ''
        in: body
        name: body
        required: true
        schema: {$ref: '#/definitions/Request'}
      produces: [application/json]
      responses:
        '200':
          description: ''
          examples: {}
          schema: {$ref: '#/definitions/Response'}
      tags: [a service]
  /plus_one/{val}:
    get:
      description: Returns an incremented value
      operationId: app.plus_one
      parameters:
      - {description: value that need to be incremented, format: int32, in: path,
        name: val, required: true, type: integer}
      responses:
        200:
          description: successful operation
          schema: {$ref: '#/definitions/Plusoneret'}
produces: [application/json]
schemes: [http]
swagger: '2.0'
