# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountReq',
            fields=[
                ('string', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
