# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisdis1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nasabah',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('saldo', models.IntegerField()),
            ],
        ),
    ]
